// examples/browser/react-app/src/App.tsx
import React, { useEffect } from 'react';
import logo from './logo.svg';
import './App.css';
import { track, identify, setGroup, groupIdentify, Identify } from '@amplitude/analytics-browser';

function App() {
  // useEffect(() => {
  //   track('Page View', {
  //     name: 'App',
  //   });
  // }, []);

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <h2>Amplitude Analytics Browser Example with React</h2>

        <button onClick={() => identify(new Identify().set('role', 'engineer'))}>
          Identify
        </button>

        <button onClick={() => setGroup('org', 'engineering')}>
          Group
        </button>

        <button onClick={() => groupIdentify('org', 'engineering', new Identify().set('technology', 'react.js'))}>
          Group Identify
        </button>

        <button onClick={() => track('Button Click', { name: 'App' })}>
          Track
        </button>
      </header>
    </div>
  );
}

export default App;

// examples/vue-app/src/App.vue
<template>
  <img alt="Vue logo" src="./assets/logo.png">
  <HelloWorld msg="Amplitude Analytics Browser Example with Vue"/>
</template>

<script lang="ts">
import { Options, Vue } from 'vue-class-component';
import HelloWorld from './components/HelloWorld.vue';
import * as amplitude from '@amplitude/analytics-browser';

@Options({
  components: {
    HelloWorld,
  },
  mounted: () => {
    amplitude.track('Page View', {
      name: 'App',
    });
  },
})
export default class App extends Vue {}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
